# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Api Test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install Go mods
        run: cd api && go mod download

      - name: Run golangci-lint
        if: always()
        uses: golangci/golangci-lint-action@v3
        run: cd api && golangci-lint run

      - name: Test
        run: cd api && go test -v ./...